### ISSUE TITLE
read more expand content in place not working

### ISSUE THREAD

**Issue by mplusb** [MachoThemes/strong-testimonials#170]
When you click the read more button it opens up then disappears.
Video with the bug: https://drive.google.com/file/d/18zSZPuIA9h0mG4cHNo6pathI48pZJGP8/view

Theme installed: Twenty Twenty
Plugins: only Strong Testimonials version 2.41.1

Screenshot with the view's settings:
![screencapture-wp-admin-edit-php-2020-07-13-19-02-43](https://user-images.githubusercontent.com/26008574/87421268-54d75b00-c5df-11ea-9569-f6e8bf4fe7e2.png)

* Which browser is affected (or browsers): 
- [x] Chrome
- [x] Firefox

**Comment by giucu91** [comment]
We have a new scenario : 

1. Put a slideshow view in a widget.

The problem is that the shortcode class don't process de view( https://github.com/MachoThemes/strong-testimonials/blob/816e2d50e7c45ebbb0303d8980d56a918a038cb1/includes/class-strong-view-display.php#L94 ) only build ( https://github.com/MachoThemes/strong-testimonials/blob/816e2d50e7c45ebbb0303d8980d56a918a038cb1/includes/class-strong-view-display.php#L115 ) the view.

So the check for readmore it is only in process method so we need to add to the build method too.

This apply also to Strong_View_Slideshow class.
